import type { Metadata } from "next";
import { APP_NAME } from "@chairback/config/constants";
import {
  A,
  H2,
  LEGAL_ENTITY,
  LegalShell,
  Notice,
  P,
  Strong,
  SUPPORT_EMAIL,
  UL,
} from "@/components/legal/Legal";

export const metadata: Metadata = {
  title: `Terms of Service — ${APP_NAME}`,
  description: `The terms that govern your use of ${APP_NAME}.`,
};

export default function TermsPage() {
  return (
    <LegalShell
      title="Terms of Service"
      intro={
        <Notice>
          PLEASE READ THESE TERMS CAREFULLY. BY CREATING AN ACCOUNT OR USING THE
          SERVICE, YOU AGREE TO BE BOUND BY THESE TERMS, INCLUDING THE
          ARBITRATION AGREEMENT AND CLASS ACTION WAIVER IN SECTION 17. IF YOU DO
          NOT AGREE, DO NOT USE THE SERVICE.
        </Notice>
      }
    >
      <H2>1. Who we are and what these Terms cover</H2>
      <P>
        These Terms of Service (the <Strong>“Terms”</Strong>) are a binding
        agreement between you and {LEGAL_ENTITY} (<Strong>“{APP_NAME}”</Strong>,{" "}
        <Strong>“we”</Strong>, <Strong>“us”</Strong>, or <Strong>“our”</Strong>)
        and govern your access to and use of the {APP_NAME} websites,
        dashboards, public shop pages, rewards pages, APIs, and related services
        (collectively, the <Strong>“Service”</Strong>).
      </P>
      <P>
        {APP_NAME} is a client-retention and loyalty platform for barbershops,
        salons, and similar appointment-based personal-care businesses. The
        Service can connect to
        your scheduling account (currently Acuity Scheduling), track completed
        visits, maintain digital punch-card balances, host a public page for
        your shop, and send text messages (such as rebooking reminders and
        promotional offers) to your clients on your behalf.
      </P>
      <P>
        If you use the Service on behalf of a business, you represent that you
        have authority to bind that business, and “you” refers to that business.
      </P>

      <H2>2. The Service is a tool — your clients are yours</H2>
      <P>
        {APP_NAME} provides software. We are not a party to the relationship
        between you and your clients. You are solely responsible for the
        services you provide at your shop, the appointments you schedule, the
        prices you charge, the offers you make, and every interaction you have
        with your clients. Nothing in the Service creates a partnership, agency,
        joint venture, franchise, or employment relationship between you and{" "}
        {APP_NAME}.
      </P>

      <H2>3. Eligibility and accounts</H2>
      <UL>
        <li>
          You must be at least 18 years old and able to form a binding contract.
        </li>
        <li>
          The Service is offered for business use by barbershops, salons, and
          similar appointment-based businesses located in the United States. It
          is not offered for personal, household, or consumer use.
        </li>
        <li>
          You must provide accurate account information and keep it current.
        </li>
        <li>
          You are responsible for safeguarding your password and for all
          activity under your account. Notify us immediately at{" "}
          <A href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</A> if you suspect
          unauthorized access.
        </li>
        <li>
          We may suspend or terminate accounts that violate these Terms or that
          we reasonably believe create risk or legal exposure for us, other
          users, or message recipients.
        </li>
      </UL>

      <H2>4. Client Data you bring to the Service</H2>
      <P>
        “<Strong>Client Data</Strong>” means information about your clients
        that is imported into the Service from your scheduling provider, entered
        by you manually, or generated by the Service on your behalf — for
        example names, phone numbers, email addresses, visit history, service
        names, prices, punch balances, redemption history, and any private notes
        you record.
      </P>
      <UL>
        <li>
          As between you and {APP_NAME}, you own your Client Data. You grant us
          a non-exclusive, worldwide license to host, process, transmit, and
          display Client Data solely to provide and improve the Service, comply
          with law, and as described in our{" "}
          <A href="/privacy">Privacy Policy</A>.
        </li>
        <li>
          <Strong>
            You are solely responsible for the lawfulness, accuracy, and quality
            of your Client Data.
          </Strong>{" "}
          You represent and warrant that you have provided all notices and
          obtained all rights, consents, and permissions required by applicable
          law to collect your Client Data and to share it with us for processing
          as described in these Terms.
        </li>
        <li>
          Private notes you record about clients are visible to you and anyone
          you allow into your account. Do not record sensitive personal
          information (such as health, financial, or government-ID information)
          in notes.
        </li>
        <li>
          We act as a service provider / processor with respect to Client Data:
          we process it only on your instructions as expressed through the
          Service, we do not sell it, and we do not use your clients’ mobile
          numbers for our own marketing. See the{" "}
          <A href="/privacy">Privacy Policy</A> for details, including our
          subprocessors.
        </li>
      </UL>

      <H2>5. Text messaging — your responsibilities</H2>
      <P>
        The Service can send SMS messages to your clients on your behalf, from a
        telephone number shared across the platform, with your shop’s name in
        the message body. <Strong>You are the sender of these messages.</Strong>{" "}
        Telemarketing and text-messaging laws — including the U.S. Telephone
        Consumer Protection Act (TCPA), the FCC’s implementing rules, state
        telemarketing laws, and carrier and CTIA messaging guidelines — impose
        serious obligations and penalties (TCPA statutory damages can be $500 to
        $1,500 <em>per message</em>). By using any messaging feature you
        represent, warrant, and agree that:
      </P>
      <UL>
        <li>
          <Strong>Consent.</Strong> For every client you message through the
          Service, you have obtained the level of consent required by applicable
          law for the type of message being sent — including{" "}
          <Strong>prior express written consent</Strong> for marketing or
          promotional messages (such as promotion blasts) — and you maintain
          records proving that consent.
        </li>
        <li>
          <Strong>Opt-outs.</Strong> You will honor opt-out requests
          immediately, whether received through the Service (STOP replies, the
          dashboard opt-out controls) or directly from the client by any other
          means. You will not re-enable messaging for a client who has opted out
          unless that client has given new consent.
        </li>
        <li>
          <Strong>Content.</Strong> Your messages, templates, and promotions
          will be truthful, not misleading, and will not relate to content
          prohibited by carrier or CTIA rules (including sex, hate, alcohol,
          firearms, tobacco, or cannabis content; illegal goods or services; or
          deceptive marketing).
        </li>
        <li>
          <Strong>Timing and identity.</Strong> You are responsible for sending
          messages only at lawful times for the recipient’s location and for
          accurately identifying your shop in custom templates.
        </li>
        <li>
          <Strong>No guarantee of delivery.</Strong> Messaging depends on
          third-party carriers and providers. We do not guarantee that any
          message will be delivered, delivered on time, or displayed correctly,
          and we may impose sending caps, filters, or suspensions at any time to
          protect platform deliverability and compliance.
        </li>
      </UL>
      <P>
        We provide compliance-supporting features (automatic “Reply STOP to opt
        out” language, platform-wide opt-out enforcement, daily send caps), but{" "}
        <Strong>
          these features do not make your messaging lawful by themselves, and we
          do not provide legal advice. Compliance with messaging laws is your
          responsibility.
        </Strong>{" "}
        See our <A href="/sms">SMS Messaging Policy</A> for the disclosures that
        apply to message recipients.
      </P>

      <H2>6. Rewards, punch cards, and promotions are your offers</H2>
      <UL>
        <li>
          Rewards, punch values, earn rules, and promotions configured in the
          Service are <Strong>your</Strong> offers to <Strong>your</Strong>{" "}
          clients. {APP_NAME} only keeps score.
        </li>
        <li>
          You are solely responsible for honoring rewards and promotions, for
          their terms and availability, and for compliance with laws that may
          apply to them (including consumer-protection, advertising, coupon,
          and gift-certificate laws in your state).
        </li>
        <li>
          Punch balances and visit data may be affected by scheduling-provider
          errors, sync delays, webhook failures, or client mismatches. We do not
          guarantee that balances are error-free, and you remain responsible for
          resolving disputes with your clients about earned or redeemed rewards.
        </li>
        <li>
          We are not liable to you or to any client for any reward or promotion,
          including any failure to honor one.
        </li>
      </UL>

      <H2>7. Public pages and your content</H2>
      <P>
        The Service lets you publish a public page for your shop (including a
        bio, hours, photos, logo, and links) and personalized rewards pages for
        your clients. “<Strong>Your Content</Strong>” means all text, images,
        logos, and other material you submit.
      </P>
      <UL>
        <li>
          You grant us a non-exclusive, worldwide, royalty-free license to host,
          reproduce, and display Your Content for the purpose of operating the
          Service (for example, rendering your public page).
        </li>
        <li>
          You represent and warrant that you own or have the necessary rights to
          Your Content, and that it does not infringe any intellectual-property,
          publicity, or privacy rights (this includes photos of clients — get
          their permission before posting them).
        </li>
        <li>
          We may remove or disable any content that we reasonably believe
          violates these Terms or applicable law, or disable public pages
          entirely, at any time.
        </li>
        <li>
          Personalized rewards links contain a private token. Anyone who has a
          client’s link can view that client’s first name and rewards balance,
          so share each link only with its client.
        </li>
      </UL>

      <H2>8. Acceptable use</H2>
      <P>You will not, and will not permit anyone to:</P>
      <UL>
        <li>use the Service to violate any law or regulation;</li>
        <li>
          send spam or any message to a person who has not consented to receive
          it;
        </li>
        <li>
          upload content that is unlawful, infringing, defamatory, harassing, or
          deceptive;
        </li>
        <li>
          probe, scan, or test the vulnerability of the Service, bypass rate
          limits or authentication, or access data belonging to another shop;
        </li>
        <li>
          reverse engineer, scrape, resell, or sublicense the Service, or use it
          to build a competing product;
        </li>
        <li>
          misrepresent your identity or your affiliation with any person or
          business;
        </li>
        <li>
          use the Service for any purpose other than operating your own
          business’s client-retention program.
        </li>
      </UL>

      <H2>9. Third-party services</H2>
      <P>
        The Service interoperates with third-party services such as Acuity
        Scheduling (Squarespace), Twilio, Google (optional sign-in), and our
        hosting and database providers. Your use of a third-party service is
        governed by that third party’s own terms and privacy policy. We do not
        control third-party services and are not responsible for their acts,
        omissions, outages, data errors, or changes to their APIs. If you
        connect your scheduling account, you authorize us to access and process
        the data it returns (appointments, client records) to provide the
        Service, and you represent that doing so does not violate your agreement
        with that provider.
      </P>

      <H2>10. Fees</H2>
      <P>
        The Service is currently offered free of charge. We may introduce paid
        plans, fees, or usage limits in the future. If we do, we will give you
        reasonable advance notice, and continued use after the effective date of
        a fee constitutes acceptance. Carrier message and data rates charged to
        message recipients are always outside our control.
      </P>

      <H2>11. Intellectual property; feedback</H2>
      <P>
        The Service — including its software, design, themes, and branding — is
        owned by {LEGAL_ENTITY} and its licensors and is protected by
        intellectual-property laws. Except for the limited right to use the
        Service under these Terms, no rights are granted to you. If you send us
        feedback or suggestions, you grant us a perpetual, irrevocable,
        royalty-free license to use them without restriction or compensation.
      </P>

      <H2>12. Privacy</H2>
      <P>
        Our <A href="/privacy">Privacy Policy</A> describes how we collect, use,
        and share personal information, and is incorporated into these Terms.
      </P>

      <H2>13. Term, suspension, and termination</H2>
      <UL>
        <li>
          You may stop using the Service and close your account at any time by
          contacting <A href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</A>.
        </li>
        <li>
          We may suspend or terminate your access at any time, with or without
          notice, if you breach these Terms, create legal or deliverability
          risk, or if we discontinue the Service. Where practical we will give
          notice and a window to export your data.
        </li>
        <li>
          Upon termination we may delete your account data and Client Data
          after a reasonable period. Sections that by their nature should
          survive (including Sections 4–8 and 14–18) survive termination.
        </li>
      </UL>

      <H2>14. Disclaimers</H2>
      <Notice>
        THE SERVICE IS PROVIDED “AS IS” AND “AS AVAILABLE,” WITHOUT WARRANTY OF
        ANY KIND. TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE DISCLAIM ALL
        WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A
        PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT
        THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE; THAT MESSAGES
        WILL BE DELIVERED; THAT DATA SYNCED FROM THIRD-PARTY SERVICES WILL BE
        ACCURATE OR COMPLETE; OR THAT USE OF THE SERVICE WILL PRODUCE ANY
        PARTICULAR BUSINESS RESULT, INCLUDING CLIENT RETENTION OR REBOOKINGS.
        NOTHING IN THE SERVICE IS LEGAL ADVICE.
      </Notice>

      <H2>15. Limitation of liability</H2>
      <Notice>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW: (A) NEITHER {LEGAL_ENTITY} NOR
        ITS OWNERS, OFFICERS, EMPLOYEES, OR SUPPLIERS WILL BE LIABLE FOR ANY
        INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE
        DAMAGES, OR FOR LOST PROFITS, LOST REVENUE, LOST DATA, OR BUSINESS
        INTERRUPTION, EVEN IF ADVISED OF THE POSSIBILITY; AND (B) OUR TOTAL
        AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THE SERVICE OR THESE
        TERMS WILL NOT EXCEED THE GREATER OF (i) THE AMOUNTS YOU PAID US FOR THE
        SERVICE IN THE TWELVE (12) MONTHS BEFORE THE CLAIM AROSE AND (ii) ONE
        HUNDRED U.S. DOLLARS ($100). THESE LIMITS APPLY TO ALL CLAIMS, WHETHER
        BASED IN CONTRACT, TORT, STATUTE, OR OTHERWISE, AND ARE A FUNDAMENTAL
        BASIS OF THE BARGAIN FOR A SERVICE OFFERED AT THIS PRICE. SOME
        JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS, SO SOME OF THE ABOVE MAY
        NOT APPLY TO YOU.
      </Notice>

      <H2>16. Indemnification</H2>
      <P>
        You will defend, indemnify, and hold harmless {LEGAL_ENTITY} and its
        owners, officers, employees, and agents from and against any claims,
        damages, fines, penalties, and expenses (including reasonable attorneys’
        fees) arising out of or relating to: (a) your Client Data, including any
        failure to obtain required consents or provide required notices; (b)
        messages sent to your clients through the Service, including claims
        under the TCPA or similar laws; (c) your rewards and promotions,
        including any failure to honor them; (d) Your Content; (e) your services
        to and interactions with your clients; or (f) your breach of these Terms
        or violation of law.
      </P>

      <H2>17. Dispute resolution — arbitration and class action waiver</H2>
      <P>
        <Strong>Informal resolution first.</Strong> Before filing a claim,
        contact us at <A href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</A>{" "}
        with a description of the dispute. We will try in good faith to resolve
        it within 30 days.
      </P>
      <P>
        <Strong>Binding arbitration.</Strong> Any dispute arising out of or
        relating to these Terms or the Service that is not resolved informally
        will be resolved by binding arbitration administered by the American
        Arbitration Association under its Commercial Arbitration Rules, by a
        single arbitrator, in English. The arbitration will be conducted in the
        State of Delaware or, at your option, remotely by videoconference.
        Judgment on the award may be entered in any court of competent
        jurisdiction. Either party may instead bring an individual claim in
        small-claims court, and either party may seek injunctive relief in court
        for infringement or misuse of intellectual property or for unauthorized
        access to the Service.
      </P>
      <Notice>
        CLASS ACTION WAIVER: ALL CLAIMS MUST BE BROUGHT IN THE PARTIES’
        INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY
        PURPORTED CLASS, CONSOLIDATED, OR REPRESENTATIVE PROCEEDING. THE
        ARBITRATOR MAY NOT CONSOLIDATE CLAIMS OR PRESIDE OVER ANY FORM OF
        REPRESENTATIVE PROCEEDING.
      </Notice>
      <P>
        <Strong>Opt-out.</Strong> You may opt out of this arbitration agreement
        by emailing <A href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</A>{" "}
        within 30 days of first accepting these Terms, with the subject
        “Arbitration opt-out” and your account email. Opting out does not affect
        any other provision of these Terms.
      </P>

      <H2>18. Governing law and venue</H2>
      <P>
        These Terms are governed by the laws of the State of Delaware, without
        regard to conflict-of-law rules. For any claim not subject to
        arbitration, the state and federal courts located in Delaware have
        exclusive jurisdiction, and you consent to personal jurisdiction there.
      </P>

      <H2>19. Changes to the Service or these Terms</H2>
      <P>
        We may modify the Service at any time, and we may update these Terms
        from time to time. If a change is material, we will give notice (for
        example by email or an in-dashboard notice) before it takes effect.
        Your continued use of the Service after the effective date of updated
        Terms constitutes acceptance. If you do not agree, stop using the
        Service and close your account.
      </P>

      <H2>20. General</H2>
      <UL>
        <li>
          <Strong>Entire agreement.</Strong> These Terms, the Privacy Policy,
          and the SMS Messaging Policy are the entire agreement between you and
          us about the Service.
        </li>
        <li>
          <Strong>Severability.</Strong> If any provision is held unenforceable,
          it will be limited to the minimum extent necessary and the rest
          remains in effect.
        </li>
        <li>
          <Strong>No waiver.</Strong> Our failure to enforce a provision is not
          a waiver of it.
        </li>
        <li>
          <Strong>Assignment.</Strong> You may not assign these Terms without
          our consent; we may assign them in connection with a merger,
          acquisition, or sale of assets.
        </li>
        <li>
          <Strong>Force majeure.</Strong> We are not liable for delay or failure
          caused by events beyond our reasonable control (including carrier or
          third-party provider outages, internet failures, and acts of
          government).
        </li>
        <li>
          <Strong>Notices.</Strong> We may provide notices by email to your
          account address or through the Service. Legal notices to us go to{" "}
          <A href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</A>.
        </li>
      </UL>

      <H2>21. Contact</H2>
      <P>
        Questions about these Terms:{" "}
        <A href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</A>.
      </P>
    </LegalShell>
  );
}
