"use client";

import { useEffect, useState, useTransition } from "react";
import { Dialog } from "@/components/ui/Dialog";
import { getShopQrAction, type ShopQr } from "@/app/dashboard/booking/qrActions";
import { cn } from "@/lib/cn";

type Toast = (msg: string, kind?: "success" | "error") => void;

/**
 * SHARE YOUR BOOKING PAGE.
 *
 * "How do I book you?" is asked at the chair, in a DM, and across a counter,
 * and the answer differs every time: sometimes a link to paste, sometimes a
 * code to hold up, sometimes a file to hand a print shop. This puts all four
 * in one sheet so the barber picks the one the moment calls for.
 *
 * The dialog mechanics - portal, focus trap, focus restore, Escape, backdrop
 * click, scroll lock, ARIA, the home-indicator gap - all belong to `Dialog`.
 * 🔴 Portalling is not optional here: `.glass` sets `backdrop-filter`, which
 * makes any ancestor card a containing block for `position: fixed`, so a sheet
 * rendered in place would size itself to the CARD and sit under its own
 * backdrop. `Dialog` already portals to `document.body`; use it, never a
 * hand-rolled `fixed inset-0`.
 *
 * The QR is fetched on OPEN, not on mount: the home page renders this for
 * every barber on every load, and the code costs a server round trip that
 * almost nobody on any given load actually wants.
 */
export function ShareBookingDialog({
  open,
  onClose,
  bookUrl,
  shopName,
  toast,
}: {
  open: boolean;
  onClose: () => void;
  /** Absolute public booking URL - exactly what the QR must encode. */
  bookUrl: string;
  shopName: string;
  toast: Toast;
}) {
  const [qr, setQr] = useState<ShopQr | null>(null);
  const [failed, setFailed] = useState(false);
  const [pending, start] = useTransition();
  // `navigator.share` is missing on desktop Chrome/Firefox and on any insecure
  // origin. Detected after mount so the server and first client render agree.
  const [canShare, setCanShare] = useState(false);

  useEffect(() => {
    setCanShare(typeof navigator !== "undefined" && typeof navigator.share === "function");
  }, []);

  useEffect(() => {
    if (!open || qr || pending) return;
    setFailed(false);
    start(async () => {
      const res = await getShopQrAction(bookUrl);
      if (res.ok) setQr(res.qr);
      else setFailed(true);
    });
    // `qr` is cached across opens on purpose - the URL cannot change while the
    // page is mounted, so re-fetching it would be a round trip for nothing.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, bookUrl]);

  // Shown without the scheme: it is read at a glance, not parsed.
  const display = bookUrl.replace(/^https?:\/\//, "");

  function copy() {
    navigator.clipboard
      ?.writeText(bookUrl)
      .then(() => toast("Booking link copied", "success"))
      .catch(() => toast("Couldn't copy link", "error"));
  }

  async function share() {
    try {
      await navigator.share({
        title: shopName,
        text: `Book with ${shopName}`,
        url: bookUrl,
      });
    } catch {
      // A cancelled share sheet throws AbortError - that is the customer
      // changing their mind, not a failure, so it must not raise a red toast.
    }
  }

  return (
    <Dialog
      open={open}
      onClose={onClose}
      title="Share your booking page"
      subtitle={shopName}
    >
      <div className="flex flex-col items-center gap-4">
        {/* THE CODE. White plate on purpose: a QR needs light quiet-zone
            contrast to scan, and inverting it for the dark theme is the
            classic way to ship one that photographs but never reads. */}
        <div className="flex h-[13.5rem] w-[13.5rem] items-center justify-center rounded-2xl bg-white p-3">
          {qr ? (
            <div
              className="h-full w-full [&>svg]:h-full [&>svg]:w-full"
              // Server-generated by the `qrcode` package from a URL we
              // validated as absolute http(s) - no user-authored markup.
              dangerouslySetInnerHTML={{ __html: qr.svg }}
              role="img"
              aria-label={`QR code that opens ${display}`}
            />
          ) : (
            <span className="text-xs font-medium text-charcoal-900/60">
              {failed ? "Couldn't build the code" : "Building your code…"}
            </span>
          )}
        </div>

        <p className="text-center text-sm text-muted [overflow-wrap:anywhere]">
          Point a phone camera at this to open
          <br />
          <span className="font-medium text-offwhite">{display}</span>
        </p>

        <div className="grid w-full grid-cols-2 gap-2">
          <ActionButton onClick={copy} label="Copy link">
            <CopyMark />
          </ActionButton>

          {canShare ? (
            <ActionButton onClick={() => void share()} label="Share">
              <ShareMark />
            </ActionButton>
          ) : (
            // No share sheet on this device: the slot goes to the print flow
            // rather than rendering a button that would do nothing.
            <ActionButton
              onClick={() => window.print()}
              label="Print"
              disabled={!qr}
            >
              <PrintMark />
            </ActionButton>
          )}

          <ActionButton href={bookUrl} external label="Open page">
            <ExternalMark />
          </ActionButton>

          <ActionButton
            href={qr?.png}
            download={`${slugForFile(shopName)}-booking-qr.png`}
            label="Download"
            disabled={!qr}
          >
            <DownloadMark />
          </ActionButton>
        </div>
      </div>
    </Dialog>
  );
}

/** A filename a barber can find again in their downloads folder. */
function slugForFile(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "shop"
  );
}

/**
 * One action. 44px floor, because every one of these is tapped on a phone
 * while holding clippers.
 */
function ActionButton({
  href,
  download,
  external,
  onClick,
  label,
  disabled,
  children,
}: {
  href?: string;
  download?: string;
  external?: boolean;
  onClick?: () => void;
  label: string;
  disabled?: boolean;
  children: React.ReactNode;
}) {
  const cls = cn(
    "flex h-12 items-center justify-center gap-2 rounded-xl border border-subtle",
    "bg-charcoal-800 px-3 text-xs font-medium text-offwhite transition-colors",
    "duration-150 ease-out hover:border-gold/50 hover:text-gold",
    disabled && "pointer-events-none opacity-40",
  );

  if (href && !disabled) {
    return (
      <a
        href={href}
        download={download}
        {...(external ? { target: "_blank", rel: "noreferrer" } : {})}
        className={cls}
      >
        <span className="text-muted">{children}</span>
        {label}
      </a>
    );
  }
  return (
    <button type="button" onClick={onClick} disabled={disabled} className={cls}>
      <span className="text-muted">{children}</span>
      {label}
    </button>
  );
}

const stroke = {
  fill: "none",
  stroke: "currentColor",
  strokeWidth: 1.8,
  strokeLinecap: "round" as const,
  strokeLinejoin: "round" as const,
};

function CopyMark() {
  return (
    <svg className="h-4 w-4" viewBox="0 0 24 24" aria-hidden {...stroke}>
      <rect x="9" y="9" width="12" height="12" rx="2.5" />
      <path d="M15 5.5A2.5 2.5 0 0 0 12.5 3h-7A2.5 2.5 0 0 0 3 5.5v7A2.5 2.5 0 0 0 5.5 15" />
    </svg>
  );
}

function ShareMark() {
  return (
    <svg className="h-4 w-4" viewBox="0 0 24 24" aria-hidden {...stroke}>
      <path d="M12 3v13M8 6.5 12 3l4 3.5" />
      <path d="M5.5 12v6.5A2.5 2.5 0 0 0 8 21h8a2.5 2.5 0 0 0 2.5-2.5V12" />
    </svg>
  );
}

function ExternalMark() {
  return (
    <svg className="h-4 w-4" viewBox="0 0 24 24" aria-hidden {...stroke}>
      <path d="M14 4h6v6M20 4l-8.5 8.5" />
      <path d="M19 14.5V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h4.5" />
    </svg>
  );
}

function DownloadMark() {
  return (
    <svg className="h-4 w-4" viewBox="0 0 24 24" aria-hidden {...stroke}>
      <path d="M12 3v12M8 11.5l4 3.5 4-3.5" />
      <path d="M4 19h16" />
    </svg>
  );
}

function PrintMark() {
  return (
    <svg className="h-4 w-4" viewBox="0 0 24 24" aria-hidden {...stroke}>
      <path d="M7 9V4h10v5" />
      <rect x="3.5" y="9" width="17" height="7" rx="2" />
      <path d="M7 14h10v6H7z" />
    </svg>
  );
}
