import { NextResponse } from "next/server";
import { MOBILE_APP } from "@chairback/config/constants";

/**
 * Android App Links verification (the assetlinks.json counterpart to the AASA).
 * Android fetches this to confirm that this domain vouches for the app, which
 * is what lets an https://getchairback.com link open the app directly instead
 * of showing a chooser.
 *
 * DELIBERATELY EMPTY UNTIL A FINGERPRINT EXISTS. There is no published Android
 * build yet, and the signing certificate's SHA-256 fingerprint is generated by
 * the build - it cannot be guessed or hardcoded here. Serving a WRONG
 * fingerprint is worse than serving none: Android caches a failed verification,
 * and every device that saw the bad file keeps refusing to open the app until
 * it re-verifies. So this returns an empty array until
 * ANDROID_CERT_SHA256_FINGERPRINT is set, and a valid statement the moment it
 * is. (`eas credentials` prints the fingerprint; Play App Signing shows it
 * under Setup > App signing.)
 *
 * Same serving requirements as the AASA: exact content-type, 200, no redirect.
 */
export async function GET(): Promise<NextResponse> {
  const fingerprints = (process.env.ANDROID_CERT_SHA256_FINGERPRINT ?? "")
    .split(",")
    .map((f) => f.trim())
    .filter(Boolean);

  const body =
    fingerprints.length === 0
      ? []
      : [
          {
            relation: ["delegate_permission/common.handle_all_urls"],
            target: {
              namespace: "android_app",
              package_name: MOBILE_APP.androidPackage,
              sha256_cert_fingerprints: fingerprints,
            },
          },
        ];

  return new NextResponse(JSON.stringify(body), {
    status: 200,
    headers: {
      "Content-Type": "application/json",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
