-- The shop an account last chose to work in.
--
-- WHY. A barber can own a shop AND hold a seat on someone else's team (an
-- independent barber who joins a shop). The active shop used to live only in
-- a per-browser cookie, so the choice never reached the phone app - its
-- dashboard WebView has its own cookie jar - and a barber who joined a team
-- from the app came back to their own shop with no sign they had joined.
-- Stored on the account, the choice follows the person to every device.
--
-- 🔴 A HINT, NEVER A GRANT. Every request re-verifies it against Shop.ownerId
-- or a ShopMember seat, exactly like the cookie, so a stale value (seat
-- removed, shop deleted) falls back to the person's own shop. That is also
-- why there is no foreign key.
--
-- Additive and nullable: every existing account reads null, which is exactly
-- today's behaviour, so there is nothing to backfill.
ALTER TABLE "User" ADD COLUMN "activeShopId" TEXT;
