/**
 * Config plugin: fix the `fmt` consteval build error on Xcode 26.x.
 *
 * Xcode 26's stricter Clang rejects the compile-time format-string checking in
 * the {fmt} library that React Native (RCT-Folly) vendors:
 *   "call to consteval function fmt::basic_format_string<...> is not a constant
 *    expression"
 * The fix maintainers recommend (facebook/react-native#55601, expo/expo#44229)
 * is to disable fmt's consteval path + compile the fmt / RCT-Folly pods as C++17
 * via a Podfile post_install hook. This Expo app has no checked-in Podfile (it's
 * generated by prebuild on EAS), so we inject the hook with a config plugin.
 *
 * Remove this once RN/Expo ship a vendored fmt that compiles cleanly on Xcode 26.
 */
const { withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const HOOK = `
  # --- BEGIN fmt consteval fix (Xcode 26) ---
  installer.pods_project.targets.each do |target|
    if ['fmt', 'RCT-Folly'].include?(target.name)
      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FMT_USE_CONSTEVAL=0'
      end
    end
  end
  # --- END fmt consteval fix ---
`;

module.exports = function withFmtConstevalFix(config) {
  return withDangerousMod(config, [
    "ios",
    (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, "Podfile");
      let contents = fs.readFileSync(podfile, "utf8");

      if (contents.includes("fmt consteval fix")) return cfg; // idempotent

      // Insert our hook at the start of the existing post_install block so it
      // runs alongside Expo's own post-install steps.
      if (contents.includes("post_install do |installer|")) {
        contents = contents.replace(
          "post_install do |installer|",
          "post_install do |installer|\n" + HOOK,
        );
      } else {
        // No post_install yet (unusual) - append a complete block.
        contents += `\npost_install do |installer|\n${HOOK}\nend\n`;
      }
      fs.writeFileSync(podfile, contents);
      return cfg;
    },
  ]);
};
